### ISSUE TITLE
Hot to launch Snapchat with image from Gallery?

### ISSUE THREAD

**Issue by AndrewPiterov** [vishesh005/app_utils#1]
Firstly, thanks for package. 
And could you show how to launch Snapchat to share an image from Gallery?
I try to do as below, it opens Snapchat but not the share screen as in enclosed image below. Which *params* I should set to open the right screen to share my image?

```dart
await AppUtils.launchApp(
        iosUrlScheme: 'snapchat://',
        androidPackage: 'com.snapchat.android',
        params: {
          'imageUrl': 'path to my image'
        },
      );
```

![photo_2022-12-16 23 07 08](https://user-images.githubusercontent.com/10525569/208189067-907d066c-9929-45a0-9012-5a2c94d5915b.jpeg)

**Comment by vishesh005** [comment]
Hi @AndrewPiterov ,

Thank you for using this package. Before we get to the solution, I'd like you to provide us with a few details listed below that will help us answer your question accurately.

1. Which platform are you testing on?
2. Is the Snapchat API aware of the **imageUrl** key?
