### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by chitgoks** [vishesh005/app_utils#2]
I wish to confirm this section if this is correct because the way i understood is the opposite.

Note -> Using QUERY_ALL_PACKAGES permission may cause your app to be rejected on playstore if your app doesn't have any core functional which is
required broad package visibility (eg antivirus app that needs limit visibility to scan all apps in your device). If your app does not require QUERY_ALL_PACKAGES permission as a core functionality in your app, consider using the

```
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
 
OR

<queries>
 <package android:name="com.whatsapp.businessapp"/> 
 <package android:name="in.techbyvishesh.myapp"/>
</queries>   
```

I am confused with this part "If your app does not require QUERY_ALL_PACKAGES permission as a core functionality in your app, consider using the"

If the app does not require QUERY_ALL_PACKAGES, how the documentation says it is to add the user permission query all packages. Wouldn't that get rejected instead? The app should maybe have something that removes that permission?

Please advise.

**Comment by vishesh005** [comment]
Hi @chitgoks ,

Sorry for any confusion this documentation has caused you; I have not been active in updating this document in the last few months.
The Play Store's policy was updated last year, noting that if your app does not require all package visibility, do not use the QUERY_ALL_PACKAGES permission. Instead, use the <queries> meta tag to specify which packages you are querying. If you still require QUERY_ALL_PACKAGES permission, you have to provide a valid use case to the the Google Play store team, or your app will be rejected.

I will update this package with the latest features and updated documentation (which I promised in the document) at the end of this month or next month.

If you still have any other query related to this package then  please let me know.

Thank You

**Comment by chitgoks** [comment]
Hi @vishesh005  no worries. thank you very much for the clarification.
